teamproject/hospital/urls.py
from django.urls import path
from . import views

app_name = 'qor_app'

# QoR/urls.py
urlpatterns = [
    path('hospital/top',views.HospitalIndex.as_view(),name="hospital_index"),
    path('hospital/index', views.PatientIndex.as_view(),name="patient_index"), 
    path('hospital/<int:pk>', views.PatientDetail.as_view(),name="patient_detail"), 
    path('hospital/chart',views.ChartIndex.as_view(),name="chart_index"),
    path('hospital/chart/<int:pk>',views.ChartDetail.as_view(),name="chart_detail"),
    path('hospital/<int:pk>/chart/create',views.ChartCreate.as_view(),name="chart_create"),
    path('hospital/chart/<int:pk>/delete',views.ChartDelete.as_view(),name="chart_delete"),
    path('hospital/chart/<int:pk>/update',views.ChartUpdate.as_view(),name="chart_update"),
]
 

teamproject/qor/urls.py
from django.urls import path
from . import views

# QoR/urls.py
urlpatterns = [
    path('', views.index, name='index'),
    path('explanation', views.explanation, name='explanation'),
    path('<int:pk>', views.user_result , name='user_result'),
    path('create_medsheet',views.create_medsheet ,name='create_medsheet'),
    path('model_check', views.model_check, name="model_check"),
    path('video_feed', views.video_feed_view(), name="video_feed"),
]

teamproject/hospital/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings

# Create your models here

#病院マスタ
class Hospital(models.Model):
    hospital_id = models.CharField(max_length=10,primary_key=True)
    hospital_name = models.TextField()

#医師マスタ
class Docter(models.Model):
    hospital = models.ForeignKey(Hospital,on_delete=models.CASCADE)
    user = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)

teamproject/hospital/forms.py
from .models import *
from qor.models import *
from django import forms

class ChartForm(forms.ModelForm):

    class Meta:
        model = Chart
        fields = (
            'prescription1',
            'prescription2',
            'prescription3',
            'note',
            'medicalsheet',
        )
        labels={
           'prescription1':'処方箋1',
           'prescription2':'処方箋2',
           'prescription3':'処方箋3',
           'note':'備考',
        }


    def __init__(self,*args,**kwargs):
        medicalsheet_id = kwargs.pop('medicalsheet_id')
        super(ChartForm,self).__init__(*args, **kwargs)
        self.fields['prescription1'].widget.attrs['placeholder'] = '処方箋を記入'
        self.fields['prescription1'].widget.attrs['class'] = 'border-none text-center w-full'
        self.fields['prescription2'].widget.attrs['placeholder'] = '処方箋を記入'
        self.fields['prescription2'].widget.attrs['class'] = 'border-none text-center w-full'
        self.fields['prescription3'].widget.attrs['placeholder'] = '処方箋を記入'
        self.fields['prescription3'].widget.attrs['class'] = 'border-none text-center w-full'
        self.fields['note'].widget.attrs['placeholder'] = '備考欄'
        self.fields['note'].widget.attrs['class'] = 'border-none w-full h-full'
        self.fields['medicalsheet'].initial = Medicalsheet.objects.get(pk=medicalsheet_id)
        self.fields['medicalsheet'].widget = forms.HiddenInput()
        self.fields['medicalsheet'].widget.attrs['class'] = 'border-none w-full hidden'

teamproject/hospital/views.py
from django.shortcuts import render,redirect
from django.shortcuts import resolve_url
from django.urls import reverse_lazy
from django.utils import timezone
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.generic import *
from . import models
from qor.models import *
from . import forms
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.

class HospitalIndex(ListView):
     #患者テーブル連携
    model = User
    # レコード情報をテンプレートに渡すオブジェクト
    context_object_name = "patient_list"
    # テンプレートファイル連携
    template_name = 'hospital/top.html'


class PatientIndex(ListView):
    #患者テーブル連携
    model = User
    # レコード情報をテンプレートに渡すオブジェクト
    context_object_name = "user_list"
    # テンプレートファイル連携
    template_name = 'hospital/patient_index.html'
    #　表示件数
    paginate_by = 10


class PatientDetail(DetailView):
    #患者テーブル連携
    model = User
    # テンプレートファイル連携
    template_name = 'hospital/patient_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(pk=self.kwargs['pk'])
        #問診票ページネーション
        medical_sheets = Medicalsheet.objects.filter(user=user)
        paginator = Paginator(medical_sheets, 10)
        page = self.request.GET.get('page', 1)
        try:
    	    pages = paginator.page(page)
        except PageNotAnInteger:
    	    pages = paginator.page(1)
        except EmptyPage:
    	    pages = paginator.page(1)

        context['user'] = user
        context['page_obj'] = pages
        return context

#診断書Views処理

class ChartIndex(ListView):
    #患者テーブル連携
    model = Chart
    # レコード情報をテンプレートに渡すオブジェクト
    context_object_name = "chart_list"
    # テンプレートファイル連携
    template_name = 'hospital/chart_index.html'

    paginate_by = 10

class ChartDetail(DetailView):
    #患者テーブル連携
    model = Chart
    # テンプレートファイル連携
    template_name = 'hospital/chart_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        chart = Chart.objects.get(pk=self.kwargs['pk'])
        context['chart'] = chart
        context['medical_sheet'] = chart.medicalsheet
        context['user'] = chart.medicalsheet.user
        return context

class ChartCreate(CreateView):
    form_class = forms.ChartForm
    template_name = 'hospital/chart_form.html'

    '''
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)
    '''

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        medical_sheet = Medicalsheet.objects.get(pk=self.kwargs['pk'])
        context['medical_sheet'] = medical_sheet
        return context

    def get_form_kwargs(self):
        kwargs = super(ChartCreate, self).get_form_kwargs()
        kwargs['medicalsheet_id'] = self.kwargs['pk']
        return kwargs

    #更新後のリダイレクト先
    def get_success_url(self):
        medical_sheet = Medicalsheet.objects.get(pk=self.kwargs['pk'])
        return reverse_lazy('qor_app:patient_detail',kwargs={'pk':medical_sheet.user.id})

class ChartDelete(DeleteView):
    model = Chart 

    def get_success_url(self):
        chart = Chart.objects.get(pk=self.kwargs['pk'])
        return reverse_lazy('qor_app:patient_detail',kwargs={'pk':chart.medicalsheet.user.id})

class ChartUpdate(UpdateView):
    #form_class = forms.ChartForm
    success_url = reverse_lazy('qor_app:patient_index')
    template_name = 'hospital/chart_form.html'

    def get_form_kwargs(self):
        kwargs = super(ChartCreate, self).get_form_kwargs()
        kwargs['patient_id'] = self.kwargs['patient_pk']
        return kwargs

    #更新後のリダイレクト先
    def get_success_url(self):
        return resolve_url('qor_app:patient_detail')


#class MedicalSheetUpdate(UpdateView):

teamproject/hospital/templates/hospital/chart_detail.html
{% extends "hospital/head.html" %}
{% load static %}
<!-- 病院側カルテ閲覧画面 -->

{% block head_title %}
<title>カルテ閲覧</title>
{% endblock %}

{% block body_block %}
<div class="main">
    <section class="text-gray-600 body-font mb-10">
        <div class="flex items-center mx-auto sm:flex-row flex-col">
          <div class="sm:w-32 sm:h-32 h-20 w-20 sm:mr-10 inline-flex items-center justify-center rounded-full bg-blue-100 text-blue-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="sm:w-16 sm:h-16 w-10 h-10" viewBox="0 0 24 24">
              <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
              <circle cx="12" cy="7" r="4"></circle>
            </svg>
          </div>
          <div class="flex-grow sm:text-left text-center mt-6 sm:mt-0">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-2">User name : {{ user.username }}</h2>
            <p class="leading-relaxed text-base">
              {% if user.get_username == user.username %}
              <p>User ID : {{user.id}}</p>
              <p>email : {{user.email}}</p>
              <p>last_login : {{user.last_login}}</p>
              <p>account create day : {{user.date_joined}}</p>
              {%endif%}</p>
          </div>
        </div>
    </section>

    <div class="tab-pane fade" id="tabs-messages" role="tabpanel" aria-labelledby="tabs-profile-tab">
        <div class="flex flex-col">
            <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="py-4 inline-block min-w-full sm:px-6 lg:px-8">
                <div class="overflow-hidden">
                    <table class="min-w-full text-center">
                        <thead class="border-b bg-gray-800">
                            <tr>
                                <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                                    問診票ID</th>
                                <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                                    訪問理由</th>
                                <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                                    訪問日</th>
                                <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                                    持病</th>
                                <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                                    服役薬</th>
                                <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                                    アレルギー</th>
                                <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                                    その他</th>
                            </tr>
                                </thead>
                                <tbody>
                                    <tr class="bg-white border-b">
                                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                        {{ medical_sheet.id }}</td>
                                    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                                        {{ medical_sheet.reason }}</td>
                                    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                                        {{ medical_sheet.since_date }}</td>
                                    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                                        {{ medical_sheet.had_illnesses }}</td>
                                    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                                        {{ medical_sheet.medicine_taken }}</td>
                                    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                                        {{ medical_sheet.allergy1 }}</td>
                                    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap justify-center">
                                        {{ medical_sheet.other1 }}</td>
                                    </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    
    </div>

    <table>
        <tbody>
            <tr>
                <th class="py-3">カルテID:</th><td>{{chart.id}}</td>
            </tr>
            <tr>
                <th class="py-3">処方箋1:</th><td>{{chart.prescription1}}</td>
            </tr>
            <tr>
                <th class="py-3">処方箋2:</th><td>{{chart.prescription2}}</td>
            </tr>
            <tr>
                <th class="py-3">処方箋3:</th><td>{{chart.prescription3}}</td>
            </tr>
            <tr>
                <th class="py-10">備考欄:</th><td class="break-words text-left px-2">{{chart.note}}</td>
            </tr>
        </tbody>
    </table>
        
        <form method="POST" action="{% url 'qor_app:chart_delete' chart.id %}">
            <div class="flex flex-col md:flex-row md:justify-around text-white text-center">
                <div class="my-4 border-blue-900 border px-6 shadow-lg bg-blue-600 hover:bg-blue-900 rounded">
                    <a href="#" class="py-2">カルテ修正</a>
                </div>
                {% csrf_token %}<input class="box-border py-2 my-2  text-center border-red-900 border shadow-lg bg-red-500 hover:bg-red-900 rounded md:py-0" type="submit" value="カルテを削除する">
            </div>
        </form>
</div>
{% endblock %}

teamproject/hospital/templates/hospital/chart_index.html
{% extends "hospital/head.html" %}
{% load static %}
<!-- 病院側患者画面 -->

{% block head_title %}
<title>カルテ一覧</title>
{% endblock %}

{% block body_block %}

<div class="main">

    <div class="text-white-300 bg-green-500 p-4 text-xl mb-2 text-white items-center flex">
        <img src="{% static 'img/medsheet-32-white.png' %}" class="w-7 h-7 mr-1">
        カルテ一覧画面
    </div>

    <br>
    <p>※IDを選択することで詳細の表示・カルテの作成・処方箋の記入ができます。</p>
    <br>
    
    <div class="tab-pane fade" id="tabs-messages" role="tabpanel" aria-labelledby="tabs-profile-tab">
        <div class="flex flex-col">
            <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="py-4 inline-block min-w-full sm:px-6 lg:px-8">
                <div class="overflow-hidden">
                    <table class="min-w-full text-center">
                        <thead class="border-b bg-gray-800">
                            <tr>
                                <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                                    カルテID</th>
                                <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                                    氏名</th>
                                <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                                    作成日時</th>
                                <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                                    最終更新</th>
                            </tr>
                                </thead>
                                <tbody>
                                    <tr class="bg-white border-b">
                                    {% for chart in chart_list %}
                                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                        <a href="{% url 'qor_app:chart_detail' pk=chart.id %}">{{ chart.id }}</a></td>
                                    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                                        {{ chart.medicalsheet.user.last_name}} {{ chart.medicalsheet.user.first_name}}</td>
                                    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                                        {{ chart.diagnose_date }}</td>
                                    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                                        {{ chart.update_date }}</td>
                                    </tr>
                                    {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    
    </div>

    <nav class="nav-page">
        <ul class="page-item">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% endif %}
        
            {% for num in page_obj.paginator.page_range %}
                {% if num <= page_obj.number|add:5 and num >= page_obj.number|add:-5 %}

                    {% if page_obj.number == num %}
                        <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                    {% endif %}
                {% endif %}
            {% endfor %}

            <!-- 次へ の部分 -->
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% endif %}
        
        </ul>

    </nav>

</div>

{% endblock %}

teamproject/hospital/templates/hospital/head.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.tailwindcss.com"></script>
    <style type="text/tailwindcss">
        @layer utilities {
          .content-auto {
            content-visibility: auto;
          }
        }
      </style>
    <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block head_title %}
    {% endblock %}
</head>

<body class="flex flex-col h-screen">
    <div id="app">
        <header class="text-gray-600 body-font bg-gradient-to-r from-cyan-500 to-blue-500 shadow-md">
            <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
              <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
                <!--
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
                  <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
                </svg>
                <span class="ml-3 text-xl">QoR</span>
            -->
                <img src="{% static 'img/rogo2.png' %}" class="w-11 h-11">
              </a>
              <nav class="md:mr-auto md:ml-4 md:py-1 md:pl-4 md:border-l md:border-gray-400	flex flex-wrap flex-grow items-center text-white justify-left">
                <a class="mr-5 hover:text-gray-900" href="{% url 'qor_app:hospital_index' %}">QoRの仕組み</a>
                <a class="mr-5 hover:text-gray-900" href="{% url 'qor_app:patient_index' %}">患者一覧</a>
                <a class="mr-5 hover:text-gray-900" href="{% url 'qor_app:chart_index' %}">診断書一覧</a>
              </nav>
            </div>

          </header>
    </div>

    {% block body_block %}

    {% endblock %}

    <footer class="mt-auto">
        <div class="bg-gray-100">
            <div class="container px-5 py-6 mx-auto flex items-center sm:flex-row flex-col">
              <a class="flex title-font font-medium items-center md:justify-start justify-center text-gray-900">
                <img src="{% static 'img/rogo2.png' %}" class="w-11 h-11">
              </a>
              <p class="text-sm text-gray-500 sm:ml-6 sm:mt-0 mt-4"> 2022 QoR —
                <a href="https://twitter.com/knyttneve" rel="noopener noreferrer" class="text-gray-600 ml-1" target="_blank">@iniad-group2</a>
              </p>
              <span class="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start">
                <a class="text-gray-500">
                  <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                    <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
                  </svg>
                </a>
                <a class="ml-3 text-gray-500">
                  <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                    <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
                  </svg>
                </a>
                <a class="ml-3 text-gray-500">
                  <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                    <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
                    <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
                  </svg>
                </a>
                <a class="ml-3 text-gray-500">
                  <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="0" class="w-5 h-5" viewBox="0 0 24 24">
                    <path stroke="none" d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"></path>
                    <circle cx="4" cy="4" r="2" stroke="none"></circle>
                  </svg>
                </a>
              </span>
            </div>
          </div>
    </footer>
</body>

</html>

teamproject/hospital/templates/hospital/patient_detail.html
{% extends "hospital/head.html" %}
{% load static %}
<!-- 病院側患者詳細画面 -->

{% block head_title %}
<title>患者詳細</title>
{% endblock %}

{% block body_block %}
<div class="main">

    <section class="text-gray-600 body-font mb-10">
        <div class="flex items-center mx-auto sm:flex-row flex-col">
          <div class="sm:w-32 sm:h-32 h-20 w-20 sm:mr-10 inline-flex items-center justify-center rounded-full bg-blue-100 text-blue-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="sm:w-16 sm:h-16 w-10 h-10" viewBox="0 0 24 24">
              <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
              <circle cx="12" cy="7" r="4"></circle>
            </svg>
          </div>
          <div class="flex-grow sm:text-left text-center mt-6 sm:mt-0">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-2">User name : {{ user.username }}</h2>
            <p class="leading-relaxed text-base">
              {% if user.get_username == user.username %}
              <p>User ID : {{user.id}}</p>
              <p>email : {{user.email}}</p>
              <p>last_login : {{user.last_login}}</p>
              <p>account create day : {{user.date_joined}}</p>
              {%endif%}</p>
          </div>
        </div>
    </section>

    <div class="tab-pane fade" id="tabs-messages" role="tabpanel" aria-labelledby="tabs-profile-tab">
        <div class="flex flex-col">
            <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="py-4 inline-block min-w-full sm:px-6 lg:px-8">
                <div class="overflow-hidden">
                    <table class="min-w-full text-center">
                        <thead class="border-b bg-gray-800">
                            <tr>
                                <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                                    問診票ID</th>
                                <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                                    訪問理由</th>
                                <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                                    訪問日</th>
                                <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                                    持病</th>
                                <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                                    服役薬</th>
                                <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                                    アレルギー</th>
                                <th scope="col" class="text-sm font-medium text-white px-6 py-4">
                                    その他</th>
                            </tr>
                                </thead>
                                <tbody>
                                    <tr class="bg-white border-b">
                                    {% for medical_sheet in page_obj %}
                                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                        {{ medical_sheet.id }}</td>
                                    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                                        {{ medical_sheet.reason }}</td>
                                    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                                        {{ medical_sheet.since_date }}</td>
                                    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                                        {{ medical_sheet.had_illnesses }}</td>
                                    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                                        {{ medical_sheet.medicine_taken }}</td>
                                    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                                        {{ medical_sheet.allergy1 }}</td>
                                    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap justify-center">
                                        {% if medical_sheet.chart.id %}
                                            <a class="p-2 bg-green-300 rounded hover:bg-green-600 hover:text-white" href="{% url 'qor_app:chart_detail' pk=medical_sheet.chart.id %}">カルテ閲覧</a></td>
                                        {% else %}
                                            <a class="p-2 bg-gray-300 rounded hover:bg-gray-600 hover:text-white" href="{% url 'qor_app:chart_create' pk=medical_sheet.id %}">カルテを記入</a></td>
                                        {% endif %}
                                    </tr>
                                    {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    
    </div>

    <nav class="nav-page">
        <ul class="page-item">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% endif %}
        
            {% for num in page_obj.paginator.page_range %}
                {% if num <= page_obj.number|add:5 and num >= page_obj.number|add:-5 %}

                    {% if page_obj.number == num %}
                        <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                    {% endif %}
                {% endif %}
            {% endfor %}

            <!-- 次へ の部分 -->
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% endif %}
        
        </ul>

    </nav>
</div>

{% endblock %}